import { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { buildYardPublicUrl } from '../../utils/yardPublicUrl';
import './YardQrCard.css';

interface YardQrCardProps {
  yardId: string;
  yardName?: string;
}

export default function YardQrCard({ yardId, yardName }: YardQrCardProps) {
  const [showFullscreenQr, setShowFullscreenQr] = useState(false);
  const yardUrl = buildYardPublicUrl(yardId);

  const handleDownloadPrint = () => {
    // Open a new window with print-friendly layout
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('לא ניתן לפתוח חלון חדש. בדוק את הגדרות חסימת החלונות בדפדפן.');
      return;
    }

    // Generate QR as data URL
    const qrSvg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    qrSvg.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
    qrSvg.setAttribute('width', '400');
    qrSvg.setAttribute('height', '400');
    qrSvg.setAttribute('viewBox', '0 0 400 400');

    // For simplicity, we'll use a canvas approach
    // Create a temporary canvas to render QR
    const canvas = document.createElement('canvas');
    canvas.width = 400;
    canvas.height = 400;
    const ctx = canvas.getContext('2d');
    
    if (!ctx) {
      alert('שגיאה ביצירת תמונה להדפסה');
      return;
    }

    // Fill white background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, 400, 400);

    // Render QR code using the same component but capture it
    // For now, we'll use a simpler approach: create HTML with inline SVG
    const htmlContent = `
<!DOCTYPE html>
<html dir="rtl" lang="he">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>קוד QR - ${yardName || 'מגרש רכבים'}</title>
  <style>
    body {
      font-family: 'Heebo', Arial, sans-serif;
      margin: 0;
      padding: 2rem;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      background: white;
      text-align: center;
    }
    .yard-name {
      font-size: 2rem;
      font-weight: 600;
      margin-bottom: 1rem;
      color: #333;
    }
    .qr-container {
      margin: 2rem 0;
    }
    .instruction {
      font-size: 1.125rem;
      color: #666;
      margin-top: 1rem;
      max-width: 400px;
    }
    @media print {
      body {
        padding: 1rem;
      }
      .instruction {
        font-size: 1rem;
      }
    }
  </style>
</head>
<body>
  <h1 class="yard-name">${yardName || 'מגרש רכבים'}</h1>
  <div class="qr-container">
    <div id="qr-code"></div>
  </div>
  <p class="instruction">סרקו את הקוד כדי לראות את רכבי המגרש באתר</p>
  <script>
    // Render QR code using qrcode.react approach
    // We'll use a simple approach: embed the URL as text and let browser handle it
    // For production, you might want to use a server-side QR generation
    const qrUrl = '${yardUrl}';
    const qrDiv = document.getElementById('qr-code');
    
    // Create an img element that will be generated by a QR service
    // For now, use a simple text-based approach or embed SVG
    // Using Google Charts API as fallback (or any QR service)
    const qrImage = document.createElement('img');
    qrImage.src = 'https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=' + encodeURIComponent(qrUrl);
    qrImage.alt = 'QR Code';
    qrImage.style.width = '400px';
    qrImage.style.height = '400px';
    qrDiv.appendChild(qrImage);
    
    // Auto-print after a short delay
    setTimeout(() => {
      window.print();
    }, 500);
  </script>
</body>
</html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  return (
    <>
      <div className="yard-qr-card card">
        <div className="yard-qr-header">
          <h3 className="yard-qr-title">קוד ה-QR החכם של המגרש</h3>
          <p className="yard-qr-description">
            לקוחות שיסרקו את הקוד יראו באתר רק את רכבי המגרש שלך.
          </p>
        </div>
        <div className="yard-qr-content">
          <div className="yard-qr-preview">
            <QRCodeSVG value={yardUrl} size={160} level="M" />
          </div>
          <div className="yard-qr-actions">
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => setShowFullscreenQr(true)}
            >
              הצג QR ללקוח
            </button>
            <button
              type="button"
              className="btn btn-secondary"
              onClick={handleDownloadPrint}
            >
              הורד להדפסה
            </button>
          </div>
        </div>
      </div>

      {/* Fullscreen QR Modal */}
      {showFullscreenQr && (
        <div className="qr-modal-overlay" onClick={() => setShowFullscreenQr(false)}>
          <div className="qr-modal-content" onClick={(e) => e.stopPropagation()}>
            <button
              type="button"
              className="qr-modal-close"
              onClick={() => setShowFullscreenQr(false)}
              aria-label="סגור"
            >
              ×
            </button>
            <div className="qr-modal-body">
              <div className="qr-modal-qr">
                <QRCodeSVG value={yardUrl} size={400} level="M" />
              </div>
              <p className="qr-modal-instruction">
                בקש מהלקוח לסרוק את הקוד כדי לראות את כל רכבי המגרש באתר.
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

